### ISSUE TITLE
[Tracker] 1.0 release

### ISSUE THREAD

**Issue by aravindavk** [kadalu/moana#264]
- [ ] Packages for Ubuntu 22.04 (One minor issue while signing the packages https://github.com/kadalu-tech/pkgs/actions/runs/3385678650/jobs/5624107749)
- [ ] Container images update
- [ ] Source installation notes

**Comment by aravindavk** [comment]
- [ ] Mount script fixes https://github.com/kadalu/moana/issues/265
